[rule]
description = """
Identifies potential remote process manipulation using SetThreatContext API. This may indicate an attempt to inject code
or debug a remote process.
"""
id = "c456266f-e920-4acb-9b32-711fa7b94ca5"
license = "Elastic License v2"
name = "Remote Thread Context Manipulation"
os_list = ["windows"]
version = "1.0.9"

query = '''
api where process.Ext.api.name == "SetThreadContext" and
 process.executable != null and process.Ext.api.behaviors : ("cross-process", "hardware_breakpoint_set") and
 not (process.code_signature.subject_name :
               ("Duncan Ogilvie", "International Business Machines Corporation", "COGNOSPHERE PTE. LTD.",
                "CAPCOM CO., LTD.", "Larian Studios Games Ltd.", "Valve Corp.", "Rockstar Games, Inc.",
                "Johannes Schindelin", "Unity Technologies ApS", "Larian Studios Games Ltd.") and
      process.code_signature.trusted == true) and
 not (process.executable : "?:\\Program Files\\WindowsApps\\Microsoft.WinDbg_*\\EngHost.exe" and
      process.parent.executable : "?:\\Program Files\\WindowsApps\\Microsoft.WinDbg_*\\DbgX.Shell.exe") and
 not (process.executable : "?:\\Program Files (x86)\\WindowsApps\\Microsoft.WinDbg_*\\EngHost.exe" and
      process.parent.executable : "?:\\Program Files (x86)\\WindowsApps\\Microsoft.WinDbg_*\\DbgX.Shell.exe") and
 not process.parent.executable :
              ("?:\\Program Files (x86)\\Steam\\steam.exe", "?:\\Program Files\\Steam\\steam.exe",
               "?:\\Program Files (x86)\\Steam\\steamapps\\common\\*.exe",
               "?:\\Program Files\\cmder\\vendor\\conemu-maximus?\\ConEmu\\ConEmuC64.exe") and
 not (process.parent.executable : "?:\\Program Files (x86)\\Microsoft Visual Studio\\*\\devenv.exe" and
      process.executable : "?:\\Program Files (x86)\\Microsoft Visual Studio\\*\\msvsmon.exe") and
 not (process.parent.executable : "?:\\Program Files\\Microsoft Visual Studio\\*\\devenv.exe" and
      process.executable : "?:\\Program Files\\Microsoft Visual Studio\\*\\msvsmon.exe") and
 not (process.executable : "?:\\Windows\\System32\\cmd.exe" and process.parent.executable : "?:\\Windows\\System32\\cmd.exe" and
      process.Ext.api.summary : ("SetThreadContext( git.exe,*", "SetThreadContext( locale.exe,*"))
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0
tree = true

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
