[rule]
description = """
Detects multiple Windows Memory API calls to modify the protection of the same memory address from Kernel32 module and
in a short time window.
"""
id = "c53dfced-feba-4527-bb8a-f181bcac59bc"
license = "Elastic License v2"
name = "Suspicious Kernel32 Memory Protection"
os_list = ["windows"]
version = "1.0.2"

query = '''
sequence by process.entity_id, process.Ext.api.parameters.address, process.thread.Ext.call_stack_final_user_module.name, process.Ext.api.parameters.size with maxspan=1m
 [api where process.Ext.api.name : "VirtualProtect" and 
  process.Ext.api.summary : "*kernel32.dll*" and process.Ext.api.parameters.size == 16 and 
  process.thread.Ext.call_stack_final_user_module.name != null and 
  not process.thread.Ext.call_stack_final_user_module.name : "Kernel" and process.Ext.behaviors.network.outgoing : "*tcp*"]
 [api where process.Ext.api.name : "VirtualProtect" and 
  process.Ext.api.summary : "*kernel32.dll*" and process.Ext.api.parameters.size == 16 and 
  process.thread.Ext.call_stack_final_user_module.name != null and 
  not process.thread.Ext.call_stack_final_user_module.name : "Kernel" and process.Ext.behaviors.network.outgoing : "*tcp*"]
 [api where process.Ext.api.name : "VirtualProtect" and 
  process.Ext.api.summary : "*kernel32.dll*" and process.Ext.api.parameters.size == 16 and 
  process.thread.Ext.call_stack_final_user_module.name != null and 
  not process.thread.Ext.call_stack_final_user_module.name : "Kernel" and process.Ext.behaviors.network.outgoing : "*tcp*"]
 [api where process.Ext.api.name : "VirtualProtect" and 
  process.Ext.api.summary : "*kernel32.dll*" and process.Ext.api.parameters.size == 16 and 
  process.thread.Ext.call_stack_final_user_module.name != null and 
  not process.thread.Ext.call_stack_final_user_module.name : "Kernel" and process.Ext.behaviors.network.outgoing : "*tcp*"]
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
