[rule]
description = """
Identifies the execution of the Microsoft Diagnostic Wizard to open a diagcab file from a suspicious path and with an
unusual parent process. This may indicate an attempt to execute malicious Troubleshooting Pack Cabinet files.
"""
id = "d18721f0-dce0-4bbc-a56a-06ea511b025e"
license = "Elastic License v2"
name = "Suspicious Troubleshooting Pack Cabinet Execution"
os_list = ["windows"]
reference = ["https://irsl.medium.com/the-trouble-with-microsofts-troubleshooters-6e32fc80b8bd"]
version = "1.0.7"

query = '''
process where event.action == "start" and
 (process.name : "msdt.exe" or process.pe.original_file_name == "msdt.exe") and process.args : "/cab" and

 process.parent.name : ("firefox.exe", "chrome.exe", "msedge.exe", "explorer.exe", "brave.exe", "whale.exe", "browser.exe",
  "dragon.exe", "vivaldi.exe", "opera.exe", "iexplore", "firefox.exe", "waterfox.exe", "iexplore.exe", "winrar.exe",
  "winrar.exe", "7zFM.exe", "outlook.exe", "winword.exe", "excel.exe") and

 process.args : ("?:\\Users\\*\\Downloads\\*",
                 "\\\\*",
                 "?:\\Users\\*\\Content.Outlook\\*",
                 "?:\\Users\\Public\\*",
                 "?:\\Users\\*\\AppData\\*",
                 "http*",
                 "ftp://*")
'''

min_endpoint_version = "7.15.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
