[rule]
description = """
Identifies attempts to load a Windows network DLL with a delay of at least 5 minutes after the process started. This may
indicate an attempt to evade detection via time based evasion techniques or execution of extra post exploitation modules
that requires those DLLs.
"""
id = "9bbcc138-3adb-41a5-b61a-787260b6492d"
license = "Elastic License v2"
name = "Delayed Load of a Windows Network Module"
os_list = ["windows"]
version = "1.0.5"

query = '''
sequence by process.entity_id with maxspan=1m
[library where process.uptime >= 300 and

  dll.name : ("ws2_32.dll", "wininet.dll", "winhttp.dll", "msxml3.dll") and

  not user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20") and 

  process.thread.Ext.call_stack_summary : "?*" and
  (
   process.name : ("wscript.exe", "cscript.exe", "rundll32.exe", "regsvr32.exe", "mshta.exe") or
   (process.executable : ("?:\\Users\\Public\\*", "?:\\ProgramData\\*") and (process.code_signature.status : "errorBadDigest" or process.code_signature.exists == false))
  ) and

  not (process.name : ("rundll32.exe", "regsvr32.exe") and
       _arraysearch(process.thread.Ext.call_stack, $entry,
                   $entry.symbol_info : ("?:\\Program Files\\*.dll*",
                                         "?:\\Program Files (x86)\\*.dll*",
                                         "?:\\Windows\\assembly\\NativeImages*",
                                         "?:\\Windows\\System32\\DriverStore*",
                                         "?:\\Windows\\Sys*\\TSWorkspace.dll!*", 
                                         "?:\\Windows\\SysWOW64\\f_policy.dll!LoginFSNEx*"))) and
  not (dll.name : "msxml3.dll" and not process.name : ("cscript.exe", "wscript.exe"))
  ]
 [network where event.action == "connection_attempted" and
  network.direction == "egress" and network.transport == "tcp" and
  source.port >= 49152 and not destination.address : ("127.*", "::1")]
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1497"
name = "Virtualization/Sandbox Evasion"
reference = "https://attack.mitre.org/techniques/T1497/"
[[threat.technique.subtechnique]]
id = "T1497.003"
name = "Time Based Evasion"
reference = "https://attack.mitre.org/techniques/T1497/003/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"

[[threat.technique]]
id = "T1573"
name = "Encrypted Channel"
reference = "https://attack.mitre.org/techniques/T1573/"


[threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[internal]
min_endpoint_version = "8.8.0"
