[rule]
description = """
Identifies attempts to modify the permissions or write to Microsoft Anti Malware Scan Interface or Windows Lock Down
Policy related DLLs from memory. This may indicate an attempt to tamper with certain Windows native protections.
"""
id = "586bf106-b208-45fc-9401-727664175ca0"
license = "Elastic License v2"
name = "AMSI or WLDP Bypass via Memory Patching"
os_list = ["windows"]
reference = [
    "https://aidenpearce369.github.io/offsec/AMSI-Memory-Bypass/",
    "https://modexp.wordpress.com/2019/06/03/disable-amsi-wldp-dotnet/",
    "https://github.com/S3cur3Th1sSh1t/Amsi-Bypass-Powershell/blob/master/README.md#Patch-the-providers-DLL-of-Microsoft-MpOav.dll",
]
version = "1.0.6"

query = '''
api where 
 process.Ext.api.name : ("VirtualProtect*", "WriteProcessMemory*") and 
 process.Ext.api.summary : ("* amsi.dll*", "* mpoav.dll*", "* wldp.dll*") and 
 process.executable != null and process.parent.executable != null and process.thread.Ext.call_stack_summary : "?*" and

 /* Third party AV/EDR DLLs */
 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("?:\\program files\\*.dll*", "?:\\program files (x86)\\*.dll*")) and
 not _arraysearch(process.thread.Ext.call_stack, $entry,
                                                 $entry.symbol_info: ("?:\\Windows\\SysWOW64\\esensordbi.dll*",
                                                                      "?:\\Windows\\System32\\esensordbi.dll*",
                                                                      "?:\\Windows\\System32\\umppc*.dll*",
                                                                      "?:\\Windows\\FireEye\\AppMonitorDll*.dll*",
                                                                      "?:\\Windows\\SysWOW64\\apphelp.dll*",
                                                                      "?:\\Windows\\SysWOW64\\apphelp.dll*",
                                                                      "?:\\Windows\\apppatch\\AppPatch*\\exploitblocker.dll*", 
                                                                      "?:\\windows\\system32\\hmpalert.dll!*", 
                                                                      "?:\\windows\\sys*\\driverstore\\filerepository\\*\\printconfig.dll!ServiceMain*",
                                                                      "?:\\program files*\\bitdefender\\endpoint security\\*.dll!*",
                                                                      "?:\\program files*\\atsecclient\\*\\atsecclientapi.dll*",
                                                                      "?:\\program files*\\n-able technologies\\avdefender\\*")) and
 not process.executable : 
           ("?:\\Program Files (x86)\\SAAZOD\\BaseComponents\\PatchManagement\\ZPMAuto.exe", 
            "?:\\Program Files\\SAAZOD\\BaseComponents\\PatchManagement\\ZPMAuto.exe", 
            "?:\\Program Files (x86)\\F-Secure\\PSB\\fssua.exe", 
            "?:\\Program Files\\F-Secure\\PSB\\fssua.exe") and 
 not (user.id : "S-1-5-18" and 
      process.executable : ("?:\\Program Files\\*.exe", "?:\\Program Files (x86)\\*.exe") and process.code_signature.trusted == true) and 
 not (process.executable : ("?:\\Windows\\System32\\msiexec.exe", "?:\\Windows\\SysWOW64\\msiexec.exe") and process.Ext.api.summary : "* wldp.dll*") and
 not (process.executable : "?:\\Program Files*\\internet explorer\\iexplore.exe" and 
      process.Ext.api.summary : ("* mpoav.dll*", "* wldp.dll*") and 
      process.parent.executable : ("?:\\Program Files*\\internet explorer\\iexplore.exe", "?:\\Windows\\explorer.exe") and 
      not process.thread.Ext.call_stack_summary : "*Unbacked*") and 
 not (process.executable : "?:\\Windows\\System32\\taskhostw.exe" and user.id : "S-1-5-18" and 
      process.parent.executable : "?:\\Windows\\System32\\svchost.exe") and 
 not (process.executable : 
              ("?:\\Program Files\\Adobe\\Acrobat DC\\Acrobat\\Acrobat.exe", 
               "?:\\Program Files (x86)\\Adobe\\Acrobat DC\\Acrobat\\Acrobat.exe") and 
      process.thread.Ext.call_stack_summary == "Unknown") and
 not process.Ext.api.parameters.protection : ("R--", "") and
 not _arraysearch(process.thread.Ext.call_stack, $entry,
                  $entry.symbol_info: ("*apphelp.dll!SE_WINRT_HookObject*", "*apphelp.dll!SdbIsTagrefFromLocalDB*", "*amsi.dll!AmsiUacScan*", "*ieshims.dll!AcRedirSetEnabled*")) and
 not (process.executable : "?:\\Windows\\System32\\lsass.exe" and process.Ext.api.summary : "* wldp.dll*" and user.id : "S-1-5-18") and
 not process.thread.Ext.call_stack_summary :
                       ("ntdll.dll|bdhkm64.dll|*",
                        "ntdll.dll|Unknown|bdhkm64.dll*",
                        "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|bdhkm32.dll|*",
                        "ntdll.dll|apphelp.dll|ntdll.dll|*",
                        "ntdll.dll|Unknown|apphelp.dll|ntdll.dll*")
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1562"
name = "Impair Defenses"
reference = "https://attack.mitre.org/techniques/T1562/"
[[threat.technique.subtechnique]]
id = "T1562.001"
name = "Disable or Modify Tools"
reference = "https://attack.mitre.org/techniques/T1562/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
