[rule]
description = """
Identifies the call of code injection related Windows API with suspicious parameters that align with shellcode
execution.
"""
id = "b112cda6-6276-4cfb-ba83-b00d66257fcd"
license = "Elastic License v2"
name = "Potential ShellCode Injection via Windows API"
os_list = ["windows"]
version = "1.0.2"

query = '''
api where event.category : "intrusion_detection" and
    process.Ext.api.behaviors : ("shellcode", "allocate_shellcode", "rwx") and
    not process.thread.Ext.call_stack_summary : ("Unbacked", "*Unknown*") and 
    not (process.executable : ("?:\\Program Files\\*", "?:\\Program Files\\*") and 
         not process.name : ("winword.exe", "excel.exe", "powerpnt.exe", "MSACCESS.EXE", "MSPUB.EXE", "fltldr.exe")) and 
    not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection_provenance : "Kernel") and 
    not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : ("?:\\Program Files\\*.dll*", "?:\\Program Files (x86)\\*.dll*"))
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
