[rule]
description = """
Identifies the call of code injection related Windows API with suspicious parameters that align with shellcode
execution.
"""
id = "b112cda6-6276-4cfb-ba83-b00d66257fcd"
license = "Elastic License v2"
name = "Potential ShellCode Injection"
os_list = ["windows"]
version = "1.0.6"

query = '''
api where event.category : "intrusion_detection" and
    process.executable != null and
    process.Ext.api.behaviors : ("shellcode", "allocate_shellcode", "rwx") and

    /* noisy patterns */
    not process.thread.Ext.call_stack_summary : ("Unbacked", "*Unknown*") and
    not (process.executable : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*") and
         not process.name : ("winword.exe", "excel.exe", "powerpnt.exe", "MSACCESS.EXE", "MSPUB.EXE", "fltldr.exe")) and
    not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection_provenance : ("Kernel", "clr.dll", "coreclr.dll", "fships.dll*", "Kernel|*")) and
    not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : ("?:\\Program Files\\*.dll*", "?:\\Program Files (x86)\\*.dll*")) and
    not  process.executable : ("?:\\Windows\\System32\\msiexec.exe", "?:\\Windows\\SysWOW64\\msiexec.exe", "?:\\Windows\\SysWOW64\\DWRCST.EXE") and
    not (process.parent.executable :  "?:\\Program Files*\\Microsoft Application Virtualization Client\\sfttray.exe" and
         _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection_provenance : "dwadv.dll")) and
    not (process.code_signature.trusted == true and
         process.code_signature.subject_name :
                              ("Shenzhen HappyDog Technology Co., Ltd.", "Martin Prikryl", "Connectwise, LLC",
                               "Lenovo (Beijing) Limited", "Essential Objects, Inc.", "Datto Inc", "EngineGame",
                               "Musecy SM Ltd.", "Cheat Engine EZ", "GOG sp. z o.o", "Acer Incorporated",
                               "Realtek Semiconductor Corp.")) and
    not (process.code_signature.subject_name : "Microsoft Corporation" and process.code_signature.trusted == true and
         process.parent.executable :
                       ("?:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe",
                        "?:\\Users\\*\\AppData\\Local\\Temp\\is-*.tmp\\CodeSetup-insider-*.tmp")) and 
    not (process.executable : "Q:\\Dameware690hp\\DWRCC.exe" and 
         process.parent.executable : "?:\\Program Files (x86)\\Microsoft Application Virtualization Client\\sfttray.exe") and
    not (process.executable : "?:\\Windows\\System32\\cmd.exe" and process.Ext.api.summary : "* conemuhk64.dll*" and
         _arraysearch(process.thread.Ext.call_stack, $entry, $entry.protection_provenance : "conemuhk64.dll|cmd.exe")) and
    not (process.executable : "D:\\ICTestAutomation\\ICRunner\\TFTCitraTestRunner.exe" and
         process.thread.Ext.call_stack_summary : "ntdll.dll|wow64.dll|wow64cpu.dll|wow64.dll|ntdll.dll|kernelbase.dll|Unbacked|ip2lib32.dll") and
    not (process.executable : "?:\\users\\*\\appdata\\local\\microsoft\\teams\\current\\teams.exe" and
         _arraysearch(process.thread.Ext.call_stack, $entry,
                  $entry.symbol_info : "?:\\users\\*\\appdata\\local\\microsoft\\teams\\current\\teams.exe!?GetAllocationHandle*"))
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
