[rule]
description = """
Identifies attempt to create a heap memory allocation with executable code permission (HEAP_CREATE_ENABLE_EXECUTE
option). This may indicate an attempt to prepare for shellcode injection evading security monitoring for suspicious
VirtualAlloc API calls.
"""
id = "4d21b212-1046-41fc-98f1-b4c175594fb2"
license = "Elastic License v2"
name = "Suspicious Executable Heap Allocation"
os_list = ["windows"]
reference = ["https://learn.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapcreate"]
version = "1.0.14"

query = '''
api where process.Ext.api.name :"VirtualAlloc" and
 process.Ext.api.parameters.protection : "*X*" and process.executable != null and
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: ("*HeapCreate*", "*RtlCreateHeap*", "*RtlProtectHeap*")) and
 process.thread.Ext.call_stack_summary : "?*" and process.thread.Ext.call_stack_final_user_module.path != null and 
 not process.thread.Ext.call_stack_final_user_module.path :
                                         ("?:\\Program Files\\*",
                                          "?:\\Program Files (x86)\\*", 
                                          "\\program files\\*", 
                                          "\\program files (x86)\\*",
                                          "?:\\windows\\microsoft.net\\framework*.dll", 
                                          "\\windows\\microsoft.net\\framework*.dll", 
                                          "?:\\programdata\\dell\\drivers\\*\\installer.exe", 
                                          "?:\\windows\\system32\\driverstore\\filerepository\\*", 
                                          "\\windows\\system32\\driverstore\\filerepository\\*", 
                                          "?:\\windows\\winsxs\\*", 
                                          "\\windows\\winsxs\\*", 
                                          "?:\\windows\\system32\\atiumd64.dll", 
                                          "\\windows\\system32\\atiumd64.dll") and 
 not process.thread.Ext.call_stack_final_user_module.name : ("gtsvm.dll", "wd*vm.dll", "Unknown") and 
 not process.thread.Ext.call_stack_summary : 
          ("*|clr.dll|*", "*mscorwks.dll*", "*mscoreei.dll*", "*mscoree.dll|ntdll.dll*", "*coreclr.dll*", 
           "ntdll.dll|hmpalert.dll|ntdll.dll|kernelbase.dll|*", "ntdll.dll|tmmon64.dll|Unknown", 
           "*ntdll.dll|kernelbase.dll|gtsvm.dll", "*ntdll.dll|kernelbase.dll|wd???vm.dll*", 
           "ntdll.dll|tmmon64.dll|Unknown", "ntdll.dll|hmpalert.dll|ntdll.dll|*", "ntdll.dll|kernelbase.dll|d3dcompiler_??.dll|*", 
           "ntdll.dll|kernelbase.dll|microsoft.csharp.ni.dll|*") and
 not process.executable :
             ("?:\\Program Files (x86)\\*.exe",
              "?:\\Program Files\\*.exe",
              "?:\\Windows\\System32\\DriverStore\\FileRepository\\*",
              "E:\\*PortableCase\\Dependencies\\Sandbox\\stubcache\\CefSharp.BrowserSubprocess.exe",
              "C:\\Steam\\steamapps\\common\\Farlight 84\\WindowsClient\\Solarland\\Binaries\\Win64\\SolarlandClient-Win64-Shipping.exe", 
              "?:\\Windows\\System32\\DriverStore\\FileRepository\\icst_service.inf_amd64_*\\intel_cst_helper_service.exe", 
              "?:\\ProgramData\\Dell\\drivers\\*\\Installer.exe", 
              "?:\\Windows\\Microsoft.NET\\Framework*\\mscorsvw.exe", 
              "?:\\Windows\\Microsoft.NET\\Framework*\\ngentask.exe", 
              "?:\\Windows\\System32\\backgroundTaskHost.exe", 
              "?:\\Windows\\SystemApps\\Microsoft.Windows.Search_*\\SearchApp.exe", 
              "?:\\Windows\\Lenovo\\ImController\\Service\\Lenovo.Modern.ImController.exe", 
              "?:\\Program Files\\windev\\AD_Voyager\\AD_voyager.exe") and
 not (process.code_signature.subject_name :
           ("Atera Networks Ltd", "Riot Games, Inc.", "IObit CO., LTD", "IObit Information Technology",
            "Shanghai Lilith Network Technology Co., Ltd.", "OKIGAMES OYUN VE YAZILIM HİZMETLERİ LİMİTED ŞİRKETİ",
            "Code Systems Corporation", "ACL INFORMATIQUE", "Slack Technologies, LLC") and
      process.code_signature.trusted == true) and 
 not (process.name : "powershell.exe" and process.command_line : "*\\CCM\\SystemTemp\\*.ps*" and user.id : "S-1-5-18")
'''

min_endpoint_version = "8.10.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.10.0"
