[rule]
description = """
Identifies the execution of a suspicious MsiExec child process. Adversaries may abuse Windows Installers for initial
access and delivery of malware.
"""
id = "877c6bd9-8df1-4a15-aa97-2a091731b15d"
license = "Elastic License v2"
name = "Suspicious MsiExec Child Process"
os_list = ["windows"]
version = "1.0.6"

query = '''
process where event.action == "start" and
   not user.id : "S-1-5-18" and

   (process.parent.name : "msiexec.exe" or
    process.parent.executable : "?:\\WINDOWS\\Installer\\MSI*.tmp") and

  (
    (process.name : ("regsvr32.exe", "rundll32.exe") and process.args : ("scrobj.dll", "?:\\Users\\*\\AppData\\*", "?:\\ProgramData\\*", "?:\\Users\\Public\\*", "-e")) or

    (process.parent.args : "/DontWait" and process.parent.args : "/HideWindow") or

    (process.name : "cmd.exe" and process.command_line : ("*start*microsoft-edge:*", "*reg add*", "*fodhelper.exe*")) or


    process.executable : ("?:\\Users\\*\\Documents\\*", "?:\\Users\\Public\\*", "?:\\ProgramData\\*", "?:\\Users\\*\\AppData\\Roaming\\*") or

    process.name : ("wscript.exe", "cscript.exe") or

    (process.name : "powershell.exe" and
     process.command_line : ("*Software\\Classes\\CLSID*", "*Reflection.Assembly*", "*::Load*",
     "?:\\Users\\*\\AppData\\Local\\Temp\\pss*.tmp.ps1", "* -enc *", "* -ec *", "*WebClient*", "*DownloadFile*", "*DownloadString*", "*iex)*"))
    ) and

    /* noisy FP patterns */
    not (process.name : "rundll32.exe" and process.command_line : ("*zzzzInvokeManagedCustomActionOutOfProc*", "*MSI*.tmp,WiseElevateRun*")) and

    not (process.name : ("wscript.exe", "cscript.exe") and process.args : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*")) and

    not (process.executable : "?:\\ProgramData\\*" and (process.Ext.token.integrity_level_name : "high" or process.args : "*uninstall*")) and

    not (process.executable : "?:\\Users\\*\\AppData\\Roaming\\*" and (process.code_signature.exists == true or process.Ext.token.integrity_level_name : "high")) and

    not (process.name : "powershell.exe" and
         process.parent.command_line :
               ("*\\AppData\\Roaming\\Browser Extension\\*",
                "*\\AppData\\Roaming\\Browser Assistant\\*",
                "*\\AppData\\Roaming\\BBWC\\*",
                "*$env:APPDATA*/Browser Extension/*")) and 
                
    not (process.name : "regsvr32.exe" and process.args :  "/i:user" and process.args : "/n") and
    not (process.executable : "?:\\ProgramData\\*\\*\\*" and process.code_signature.trusted == true)
'''

min_endpoint_version = "7.15.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "System Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.007"
name = "Msiexec"
reference = "https://attack.mitre.org/techniques/T1218/007/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
