[rule]
description = """
Identifies the load of a DLL from a network file share followed by a suspicious DLL load event. Adversaries may leverage
this technique to avoid dropping to disk the malicious payload on the targeted machine.
"""
id = "c9674e88-8423-442a-9712-ba6271bcff10"
license = "Elastic License v2"
name = "Suspicious Image Load from SMB Shares"
os_list = ["windows"]
version = "1.0.14"

query = '''
sequence by process.entity_id with maxspan=1m
 [library where dll.path : "\\Device\\Mup\\*" and not startswith~(dll.name, process.name) and 
  not _arraysearch(process.thread.Ext.call_stack, $entry,
                   $entry.symbol_info : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*", "?:\\Windows\\Sys*\\tmumh\\*\\tmmon.dll+*")) and
  not process.executable :
            ("?:\\Windows\\System32\\sdiagnhost.exe",
             "?:\\Windows\\System32\\CompPkgSrv.exe",
             "?:\\Windows\\System32\\backgroundTaskHost.exe") and 
  not process.thread.Ext.call_stack_summary : "ntdll.dll|kernelbase.dll|jvm.dll|java.dll|Unbacked"
  ]
 [library where
  process.executable != null and
  (
   (dll.name : ("ws2_32.dll", "dnsapi.dll", "wininet.dll", "psapi.dll") and
    process.thread.Ext.call_stack_summary : "*Unbacked*" and
    not process.thread.Ext.call_stack_summary :
            ("*mscorlib.dll*","*|clr.dll*", "*coreclr.dll*", "*mscoreei.dll*", "*mscoree.dll*", "*system.ni.dll*",
             "*mscorlib.ni.dll*", "*mscorwks.dll*", "*mscorsvc.dll*", "*system.private.corelib.dll*",
             "*java.dll|Unbacked*", "*system.data.ni.dll*", "*|ntdll.dll|Unbacked|ntdll.dll", "*windowsbase.ni.dll*",
             "*presentationframework.ni.dll*", "ntdll.dll|Unbacked")) or

   dll.name : ("vaultcli.dll", "dsquery.dll", "System.Management.Automation.dll") or

   (dll.name : "ntdll.dll" and dll.Ext.load_index >= 2)
  ) and 
  not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*"))]
'''

min_endpoint_version = "8.7.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1021"
name = "Remote Services"
reference = "https://attack.mitre.org/techniques/T1021/"
[[threat.technique.subtechnique]]
id = "T1021.002"
name = "SMB/Windows Admin Shares"
reference = "https://attack.mitre.org/techniques/T1021/002/"



[threat.tactic]
id = "TA0008"
name = "Lateral Movement"
reference = "https://attack.mitre.org/tactics/TA0008/"

[internal]
min_endpoint_version = "8.7.0"
