[rule]
description = "Identifies suspicious writes to the memory space of a remote process. this may indicate a code injection attempt."
id = "33270c59-e034-4e5b-accb-b6a23681a0d3"
license = "Elastic License v2"
name = "Suspicious Memory Write to a Remote Process"
os_list = ["windows"]
version = "1.0.4"

query = '''
api where process.Ext.api.name == "WriteProcessMemory" and process.executable : "?:\\*" and
 process.Ext.api.behaviors == "cross-process" and process.Ext.api.parameters.size >= 10000 and
 not process.executable :
             ("?:\\Program Files\\*.exe",
              "?:\\Program Files (x86)\\*.exe",
              "?:\\Windows\\System32\\lsass.exe",
              "?:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*.exe") and
 not _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info : ("*msys-*.dll!_feinitialise*", "*cygwin*.dll!setprogname+*")) and
 not (stringcontains~(process.Ext.api.summary, process.name) and not process.executable : "?:\\Windows\\*") and
 not (process.code_signature.trusted == true and process.code_signature.subject_name : ("GEOVISION INC.", "COMPUTACION EN ACCION SA DE CV"))
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
