[rule]
description = """
Identifies the load of an unsigned or untrusted DLL by a trusted binary followed by calling VirtualProtect API to change
memory permission to execute or write. This may indicate execution via DLL sideloading to perform code injection.
"""
id = "8858facd-72b7-495c-831c-4d8ad12a8bf0"
license = "Elastic License v2"
name = "VirtualProtect API Call from an Unsigned DLL"
os_list = ["windows"]
version = "1.0.4"

query = '''
sequence by process.entity_id
[library where
   (dll.Ext.relative_file_creation_time <= 900 or
    dll.Ext.relative_file_name_modify_time <= 900 or
    dll.Ext.device.product_id : ("Virtual DVD-ROM", "Virtual Disk","USB *") or 
    dll.path : ("\\Device\\Mup\\*", "?:\\Users\\Public\\*", "?:\\Windows\\Tasks\\*", "?:\\ProgramData\\*")) and 
    not endswith~(dll.name, process.name)  and 
    not dll.code_signature.status : ("trusted", "errorExpired", "errorCode_endpoint*") and dll.hash.sha256 != null and
    not dll.path : ("?:\\Windows\\Installer\\*",
                    "?:\\Windows\\System32\\DriverStore\\FileRepository\\*",
                    "?:\\Windows\\SysWOW64\\DriverStore\\FileRepository\\*",
                    "?:\\Program Files\\*",
                    "?:\\Program Files (x86)\\*",
                    "?:\\Windows\\assembly\\*")] as event0
[api where
  process.Ext.api.name : "VirtualProtect*" and process.Ext.api.parameters.protection : ("*X*", "*W*") and
  _arraysearch(process.thread.Ext.call_stack, $entry, stringcontains~($entry.protection_provenance, event0.dll.name))]
 until [process where event.action:"end"]
'''

min_endpoint_version = "8.8.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"

[[threat.technique]]
id = "T1574"
name = "Hijack Execution Flow"
reference = "https://attack.mitre.org/techniques/T1574/"
[[threat.technique.subtechnique]]
id = "T1574.002"
name = "DLL Side-Loading"
reference = "https://attack.mitre.org/techniques/T1574/002/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
