[rule]
description = """
Identifies potential remote process manipulation using SetThreatContext API. This may indicate an attempt to inject code
or debug a remote process.
"""
id = "c456266f-e920-4acb-9b32-711fa7b94ca5"
license = "Elastic License v2"
name = "Remote Thread Context Manipulation"
os_list = ["windows"]
version = "1.0.13"

query = '''
api where process.Ext.api.name == "SetThreadContext" and
 process.executable != null and process.Ext.api.behaviors : ("cross-process", "hardware_breakpoint_set") and
 not process.Ext.api.summary : "SetThreadContext( *, [ OSError ] )" and 
 not (process.code_signature.subject_name :
               ("Duncan Ogilvie", "International Business Machines Corporation", "COGNOSPHERE PTE. LTD.",
                "CAPCOM CO., LTD.", "Larian Studios Games Ltd.", "Valve Corp.", "Rockstar Games, Inc.",
                "Johannes Schindelin", "Unity Technologies ApS", "Larian Studios Games Ltd.", 
                "Paradox Interactive AB (publ)", "CD PROJEKT SPÓŁKA AKCYJNA", "JetBrains s.r.o.",
                "Open Source Developer, Maksim Moisiuk", "Take-Two Interactive Software, Inc.", 
                "Take-Two Interactive Software, Inc.", "Facepunch Studios Ltd", "Nox Limited", "Maksim Moisiuk", 
                "Activision Publishing Inc", "OpenJS Foundation", "Maksim Moisiuk", "Ubisoft Entertainment Sweden AB") and
      process.code_signature.trusted == true) and 
 not (process.executable : "?:\\Users\\*\\AppData\\Local\\Programs\\Python\\*.exe" and 
      process.code_signature.subject_name : "Python Software Foundation" and process.code_signature.trusted == true) and 
 not (process.executable : "?:\\Program Files\\WindowsApps\\Microsoft.WinDbg_*\\EngHost.exe" and
      process.parent.executable : "?:\\Program Files\\WindowsApps\\Microsoft.WinDbg_*\\DbgX.Shell.exe") and
 not (process.executable : "?:\\Program Files (x86)\\WindowsApps\\Microsoft.WinDbg_*\\EngHost.exe" and
      process.parent.executable : "?:\\Program Files (x86)\\WindowsApps\\Microsoft.WinDbg_*\\DbgX.Shell.exe") and
 not process.parent.executable :
              ("?:\\Program Files (x86)\\Steam\\steam.exe", "?:\\Program Files\\Steam\\steam.exe",
               "?:\\Program Files (x86)\\Steam\\steamapps\\common\\*.exe",
               "?:\\Program Files\\cmder\\vendor\\conemu-maximus?\\ConEmu\\ConEmuC64.exe", 
               "?:\\Program Files (x86)\\Windows Kits\\*\\Debuggers\\x64\\cdb.exe", 
               "?:\\Program Files\\Microsoft Visual Studio\\*\\devenv.exe",
               "?:\\Program Files (x86)\\Microsoft Visual Studio\\*\\devenv.exe",
               "?:\\Program Files (x86)\\Steam\\steamapps\\common\\*.exe", 
               "C:\\Program Files\\OpenModelica1.21.0-64bit\\bin\\OMEdit.exe") and 
 not process.executable :
              ("?:\\Program Files (x86)\\Windows Kits\\*\\Debuggers\\*\\cdb.exe", 
               "?:\\Program Files\\Windows Kits\\*\\Debuggers\\*\\cdb.exe",
               "?:\\Program Files (x86)\\Windows Kits\\*\\Debuggers\\*\\cdb.exe",
               "?:\\Program Files\\Microsoft Visual Studio\\*\\devenv.exe",
               "?:\\Program Files (x86)\\Microsoft Visual Studio\\*\\devenv.exe",
               "?:\\Program Files (x86)\\Steam\\steamapps\\common\\*.exe", 
               "?:\\Program Files\\DebugDiag\\DbgHost.exe", 
               "?:\\Program Files (x86)\\DebugDiag\\DbgHost.exe", 
               "?:\\Program Files\\IDA Freeware 8.3\\ida64.exe", 
               "?:\\Program Files\\Git\\usr\\bin\\env.exe", 
               "?:\\Windows\\System32\\cmd.exe", 
               "?:\\Windows\\System32\\net.exe",
               "?:\\Windows\\explorer.exe", 
               "?:\\Program Files\\nodejs\\node.exe",
               "?:\\ION\\mingw64\\bin\\gdborig.exe",
               "?:\\mingw64\\bin\\gdborig.exe",
               "?:\\Program Files\\Git\\usr\\bin\\sh.exe",
               "?:\\Program Files\\IDA Pro ?.?\\ida64.exe",
               "D:\\SteamLibrary\\steamapps\\common\\*",
               "E:\\SteamLibrary\\steamapps\\common\\*",
               "?:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe", 
               "?:\\Program Files (x86)\\Microsoft Office\\root\\Office??\\EXCEL.EXE", 
               "G:\\SteamLibrary\\steamapps\\common\\Hydroneer\\Mining\\Binaries\\Win64\\Mining-Win64-Shipping.exe")
'''

min_endpoint_version = "8.8.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0
tree = true

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.8.0"
