[rule]
description = """
Identifies the execution of commonly abused Windows utilities via a delayed Ping execution. This behavior is often
observed during malware installation and is consistent with an attacker attempting to evade detection.
"""
id = "7615ca4b-c291-4f05-9488-114b6bf99157"
license = "Elastic License v2"
name = "Delayed Execution via Ping"
os_list = ["windows"]
version = "1.0.5"

query = '''
sequence by process.parent.entity_id with maxspan=1m
  [process where event.action == "start" and process.name : "ping.exe" and
   process.parent.name : "cmd.exe" and not user.id : "S-1-5-18" and
   process.args : "-n" and
   process.args : ("8.8.*", "localhost", "127.*", "0.0.*.*")]
  [process where event.action == "start" and
   process.parent.name : "cmd.exe" and
   process.name : ("rundll32.exe",
                   "powershell.exe",
                   "mshta.exe",
                   "msbuild.exe",
                   "certutil.exe",
                   "regsvr32.exe",
                   "powershell.exe",
                   "cscript.exe",
                   "wscript.exe",
                   "wmic.exe",
                   "installutil.exe",
                   "msxsl.exe",
                   "Microsoft.Workflow.Compiler.exe",
                   "ieexec.exe",
                   "iexpress.exe",
                   "RegAsm.exe",
                   "installutil.exe",
                   "RegSvcs.exe",
                   "RegAsm.exe") or
    (process.executable : "?:\\Users\\*\\AppData\\*.exe" and not process.code_signature.trusted == true) and
    not process.args : ("?:\\Program Files\\*", "?:\\Program Files (x86)\\*") and
    not (process.name : ("openssl.exe", "httpcfg.exe", "certutil.exe") and process.parent.command_line : "*ScreenConnectConfigurator.cmd*") and
    not (process.pe.original_file_name : "DPInst.exe" and process.command_line : "driver\\DPInst_x64  /f ") and
    not (process.name : "powershell.exe" and process.args : "Write-Host ======*")
    ]
'''

[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"

[[threat.technique.subtechnique]]
id = "T1059.005"
name = "Visual Basic"
reference = "https://attack.mitre.org/techniques/T1059/005/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1216"
name = "Signed Script Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1216/"

[[threat.technique]]
id = "T1218"
name = "Signed Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.003"
name = "CMSTP"
reference = "https://attack.mitre.org/techniques/T1218/003/"

[[threat.technique.subtechnique]]
id = "T1218.004"
name = "InstallUtil"
reference = "https://attack.mitre.org/techniques/T1218/004/"

[[threat.technique.subtechnique]]
id = "T1218.005"
name = "Mshta"
reference = "https://attack.mitre.org/techniques/T1218/005/"

[[threat.technique.subtechnique]]
id = "T1218.009"
name = "Regsvcs/Regasm"
reference = "https://attack.mitre.org/techniques/T1218/009/"

[[threat.technique.subtechnique]]
id = "T1218.010"
name = "Regsvr32"
reference = "https://attack.mitre.org/techniques/T1218/010/"

[[threat.technique.subtechnique]]
id = "T1218.011"
name = "Rundll32"
reference = "https://attack.mitre.org/techniques/T1218/011/"


[[threat.technique]]
id = "T1220"
name = "XSL Script Processing"
reference = "https://attack.mitre.org/techniques/T1220/"


[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
