[rule]
description = """
Identifies the execution of a Windows scripting interpreter that invokes an instance of Microsoft Office application via
COM to potentially execute malicious Visual Basic macro code.
"""
id = "b4390574-78e4-4408-b1aa-be3fc4d1e2f1"
license = "Elastic License v2"
name = "Suspicious Macro Execution via Windows Scripts"
os_list = ["windows"]
version = "1.0.13"

query = '''
sequence by process.entity_id with maxspan=1m
 [process where event.action == "start" and
  process.Ext.effective_parent.name : ("wscript.exe", "cscript.exe", "mshta.exe", "powershell.exe") and
  process.name : ("outlook.exe", "excel.exe", "winword.exe", "powerpnt.exe",
                  "eqnedt32.exe", "fltldr.exe", "mspub.exe", "msaccess.exe")]
 [any where
  process.name : ("outlook.exe", "excel.exe", "winword.exe", "powerpnt.exe",
                  "eqnedt32.exe", "fltldr.exe", "mspub.exe", "msaccess.exe") and
  /* executing some Macro VBA code */
  process.thread.Ext.call_stack_summary : "*|vbe?.dll*" and
  not (event.category : "registry" and registry.key : "SOFTWARE\\Microsoft\\Office\\*\\Word\\Text Converters\\Import")]
'''

min_endpoint_version = "8.7.0"
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"

[[threat.technique.subtechnique]]
id = "T1059.005"
name = "Visual Basic"
reference = "https://attack.mitre.org/techniques/T1059/005/"

[[threat.technique.subtechnique]]
id = "T1059.007"
name = "JavaScript"
reference = "https://attack.mitre.org/techniques/T1059/007/"


[[threat.technique]]
id = "T1559"
name = "Inter-Process Communication"
reference = "https://attack.mitre.org/techniques/T1559/"
[[threat.technique.subtechnique]]
id = "T1559.001"
name = "Component Object Model"
reference = "https://attack.mitre.org/techniques/T1559/001/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[internal]
min_endpoint_version = "8.7.0"
