[rule]
description = """
Detects potential execution from a mounted device. Malware may abuse DMG files to deliver malicious code or scripts to
gain initial access.
"""
id = "c6ee0cc0-efc4-4353-bbfc-da16ebc4e1a5"
license = "Elastic License v2"
name = "Execution from a Mounted Device"
os_list = ["macos"]
version = "1.0.3"

query = '''
sequence with maxspan=3m
 [file where event.action == "mount" and
  not (process.executable : "/usr/libexec/lsd" and file.path : "/private/var/folders/*/AppTranslocation/*")] as event0
 [process where event.action == "exec" and 
  (startswith (process.args, event0.file.path) or 
   startswith (process.parent.args, event0.file.path)) and 
  
   /* FPs */ 
  not process.executable :
           ("/bin/ls",
            "/usr/bin/find",
            "/usr/bin/dirname",
            "/usr/bin/macbinary",
            "/usr/bin/arch",
            "/sbin/mount_apfs",
            "/sbin/umount",
            "/sbin/mount",
            "/usr/libexec/lsd",
            "/usr/bin/ditto",
            "/sbin/quotacheck",
            "/usr/bin/hdiutil",
            "/usr/sbin/vsdbutil",
            "/sbin/mount_smbfs",
            "/System/Library/CoreServices/backupd.bundle/Contents/Resources/brtool",
            "/System/Library/Filesystems/*/Contents/Resources/umount*",
            "/System/Library/Filesystems/*/Contents/Resources/mount*",
            "/Library/Filesystems/*/Contents/Resources/umount*",
            "/Library/Filesystems/*/Contents/Resources/mount*",
            "/System/Library/CoreServices/NetAuthAgent.app/Contents/MacOS/NetAuthSysAgent", 
            "/System/Library/Filesystems/apfs.fs/Contents/Resources/mount_apfs",
            "/System/Library/Filesystems/hfs.fs/Contents/Resources/mount_hfs",
            "/System/Library/CoreServices/NetAuthAgent.app/Contents/MacOS/NetAuthSysAgent",
            "/System/Library/PrivateFrameworks/MobileSoftwareUpdate.framework/Versions/A/XPCServices/com.apple.MobileSoftwareUpdate.CleanupPreparePathService.xpc/Contents/MacOS/com.apple.MobileSoftwareUpdate.CleanupPreparePathService",
            "/Library/Application Support/Paragon Software/com.paragon-software.ntfs.notification-agent.app/Contents/MacOS/NotificationAgent") and

   /* Slack, Dropbox, Firefox, Teamviewer and many more legit installs - BYOV is a gap that will be covered by other rules */
   not (process.code_signature.subject_name : "Developer ID Application*" and process.code_signature.trusted == true)
   ]
'''

optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 1

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1204"
name = "User Execution"
reference = "https://attack.mitre.org/techniques/T1204/"
[[threat.technique.subtechnique]]
id = "T1204.002"
name = "Malicious File"
reference = "https://attack.mitre.org/techniques/T1204/002/"



[threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

[internal]
min_endpoint_version = "8.4.0"
