[rule]
description = """
Identifies the execution of the built-in Windows Installer, MSIEXEC, to install a remote package. Adversaries may abuse
msiexec.exe to launch local or network accessible MSI files.
"""
id = "17cd570a-979a-4806-80b5-9b3854e9d603"
license = "Elastic License v2"
name = "Potential Remote File Execution via MSIEXEC"
os_list = ["windows"]
version = "1.0.5"

query = '''
sequence with maxspan=1m
 [process where event.action == "start" and process.name : "msiexec.exe" and process.args : "/V"] by process.entity_id
 [network where process.name : "msiexec.exe" and event.action == "connection_attempted"] by process.entity_id
 [process where event.action == "start" and
  process.parent.name : "msiexec.exe" and user.id : "S-1-5-21-*" and
  not process.executable : ("?:\\Windows\\SysWOW64\\msiexec.exe",
                            "?:\\Windows\\System32\\msiexec.exe",
                            "?:\\Windows\\System32\\srtasks.exe",
                            "?:\\Windows\\SysWOW64\\srtasks.exe",
                            "?:\\Windows\\System32\\taskkill.exe",
                            "?:\\Windows\\Installer\\MSI*.tmp",
                            "?:\\Program Files\\*.exe",
                            "?:\\Program Files (x86)\\*.exe",
                            "?:\\Windows\\System32\\ie4uinit.exe",
                            "?:\\Windows\\SysWOW64\\ie4uinit.exe") and 
  not (process.code_signature.subject_name == "Citrix Systems, Inc." and process.code_signature.trusted == true) and 
  not (process.name : ("regsvr32.exe", "powershell.exe") and 
       process.Ext.token.integrity_level_name == "high" and
       process.args : ("?:\\Program Files\\*.exe", "?:\\Program Files (x86)\\*.exe"))] by process.parent.entity_id
'''

[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 2

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1566"
name = "Phishing"
reference = "https://attack.mitre.org/techniques/T1566/"
[[threat.technique.subtechnique]]
id = "T1566.001"
name = "Spearphishing Attachment"
reference = "https://attack.mitre.org/techniques/T1566/001/"



[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1218"
name = "Signed Binary Proxy Execution"
reference = "https://attack.mitre.org/techniques/T1218/"
[[threat.technique.subtechnique]]
id = "T1218.007"
name = "Msiexec"
reference = "https://attack.mitre.org/techniques/T1218/007/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "7.15.0"
