[rule]
description = """
Identifies the creation of a PDF document with Microsoft Office file extensions. An adversary may embed a malicious Word
or Excel document into a PDF document to evade some detections based on file header.
"""
id = "7d154d6c-66a0-4b4f-a585-dca74e2b877f"
license = "Elastic License v2"
name = "Office Document Delivery via a PDF File"
os_list = ["windows"]
reference = ["https://blogs.jpcert.or.jp/en/2023/08/maldocinpdf.html"]
version = "1.0.5"

query = '''
file where event.action != "deletion" and

 /* PDF header with MS Office file extension */
 file.Ext.header_bytes : "25504446*" and file.extension : "doc*" and file.path : "?:\\Users\\*" and 

 not process.executable : "?:\\Windows\\System32\\spoolsv.exe"
'''

actions = []
min_endpoint_version = "8.4.0"
[[optional_actions]]
action = "rollback"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1566"
name = "Phishing"
reference = "https://attack.mitre.org/techniques/T1566/"
[[threat.technique.subtechnique]]
id = "T1566.001"
name = "Spearphishing Attachment"
reference = "https://attack.mitre.org/techniques/T1566/001/"



[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"

[internal]
min_endpoint_version = "8.4.0"
