[rule]
description = """
Identifies a suspicious image load (taskschd.dll) from Microsoft Office processes followed by immediate task creation.
This behavior may indicate adversarial activity where a scheduled task is configured via Windows Component Object Model
(COM). This technique can be used to configure persistence and evade monitoring by avoiding the usage of the traditional
Windows binary (schtasks.exe) used to manage scheduled tasks.
"""
id = "f9fd002c-0dab-42ec-8675-0cf5af6b4a85"
license = "Elastic License v2"
name = "Scheduled Task Creation via Microsoft Office"
os_list = ["windows"]
reference = [
    "https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-and-eql-8de93338c16",
    "https://www.clearskysec.com/wp-content/uploads/2020/10/Operation-Quicksand.pdf",
    "https://research.checkpoint.com/2021/irans-apt34-returns-with-an-updated-arsenal/",
]
version = "1.0.11"

query = '''
sequence with maxspan=1m
    [library where dll.name : "taskschd.dll" and
     process.name : ("WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE")]
    [file where event.action == "creation" and process.name == "svchost.exe" and
     file.path : ("?:\\Windows\\System32\\Tasks\\*", "?:\\Windows\\SysWOW64\\Tasks\\*") and

     /* Issue #365 */
     not file.name : ("MusUx_LogonUpdateResults", "Microsoft Office ?? Sync Maintenance*")]
'''

[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[optional_actions]]
action = "rollback"

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1566"
name = "Phishing"
reference = "https://attack.mitre.org/techniques/T1566/"
[[threat.technique.subtechnique]]
id = "T1566.001"
name = "Spearphishing Attachment"
reference = "https://attack.mitre.org/techniques/T1566/001/"



[threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1053"
name = "Scheduled Task/Job"
reference = "https://attack.mitre.org/techniques/T1053/"


[threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

[internal]
min_endpoint_version = "7.15.0"
