[rule]
description = """
Identifies the load of an unsigned library by the print spooler service. Adversaries may use port monitors to run an
adversary supplied DLL during system boot for persistence or privilege escalation.
"""
id = "555cdfaa-b87d-4fbb-8ab1-869497210569"
license = "Elastic License v2"
name = "Suspicious Print Monitor Driver Loaded"
os_list = ["windows"]
reference = ["https://pentestlab.blog/2019/10/28/persistence-port-monitors/"]
version = "1.0.3"

query = '''
library where
 process.executable : ("?:\\Windows\\System32\\spoolsv.exe", "?:\\Windows\\SysWOW64\\spoolsv.exe") and
 user.id : "S-1-5-18" and
 not dll.code_signature.status : ("trusted", "errorExpired") and
 _arraysearch(process.thread.Ext.call_stack, $entry, $entry.symbol_info: "*localspl.dll!SplAddMonitor*") and 
 not dll.hash.sha256 : 
              ("2fd0dbb21a920f7be4c878ac9ba263425f6ad2e15d9bc1d9cea76a124630e3e2", 
               "d919c39a348294d378a9f7d1f100a4aef9b855f6fd4049ecd73de817388fee86",
               "e91962ad43988b52cd093222004a660202af467b69c215f6eba17dab844c3acd")
'''

min_endpoint_version = "8.7.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"
[[threat.technique.subtechnique]]
id = "T1547.010"
name = "Port Monitors"
reference = "https://attack.mitre.org/techniques/T1547/010/"



[threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

[internal]
min_endpoint_version = "8.7.0"
