[rule]
description = """
Identifies the creation of a launch agent or daemon property list file to run a program at load time and from a hidden
folder. On Linux and Mac, users can mark specific files as hidden simply by putting a "." as the first character in the
file or folder name. An adversary may establish persistence by installing a new launch agent or daemon which executes at
login.
"""
id = "c6037fad-ad13-46a6-9f7f-4deeef5ac69b"
license = "Elastic License v2"
name = "Persistence from a Hidden File via Launch Agent"
os_list = ["macos"]
version = "1.0.1"

query = '''
any where event.action == "launch_daemon" and Persistence.runatload == true and

 Persistence.args : "*/.*" and

 not (Persistence.args :  "/Users/Shared/.Printix.net/Service/Printix Service.app/Contents/MacOS/Printix Service" and
      Persistence.path : "/Library/LaunchDaemons/net.Printix.Service.plist") and

 not (process.code_signature.signing_id : "com.bomgar.bomgar-scc" and process.code_signature.trusted == true)
'''

min_endpoint_version = "8.3.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1543"
name = "Create or Modify System Process"
reference = "https://attack.mitre.org/techniques/T1543/"
[[threat.technique.subtechnique]]
id = "T1543.001"
name = "Launch Agent"
reference = "https://attack.mitre.org/techniques/T1543/001/"

[[threat.technique.subtechnique]]
id = "T1543.004"
name = "Launch Daemon"
reference = "https://attack.mitre.org/techniques/T1543/004/"


[[threat.technique]]
id = "T1547"
name = "Boot or Logon Autostart Execution"
reference = "https://attack.mitre.org/techniques/T1547/"
[[threat.technique.subtechnique]]
id = "T1547.011"
name = "Plist Modification"
reference = "https://attack.mitre.org/techniques/T1547/011/"



[threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1564"
name = "Hide Artifacts"
reference = "https://attack.mitre.org/techniques/T1564/"
[[threat.technique.subtechnique]]
id = "T1564.001"
name = "Hidden Files and Directories"
reference = "https://attack.mitre.org/techniques/T1564/001/"



[threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

[internal]
min_endpoint_version = "8.3.0"
