[rule]
description = """
Identifies attempts to bypass User Account Control (UAC) via eventvwr.exe. Attackers bypass UAC to stealthily execute
code with elevated permissions.
"""
id = "ab29a79a-b3c2-4ae4-9670-70dd0ea68a4a"
license = "Elastic License v2"
name = "UAC Bypass via Event Viewer"
os_list = ["windows"]
reference = ["https://github.com/hfiref0x/UACME"]
version = "1.0.7"

query = '''
process where event.action == "start" and
 process.parent.name : "eventvwr.exe" and
 process.Ext.token.integrity_level_name == "high" and
 not process.executable :
           ("?:\\Windows\\SysWOW64\\mmc.exe",
            "?:\\Windows\\System32\\mmc.exe",
            "?:\\Windows\\System32\\WerFault.exe",
            "?:\\Windows\\SysWOW64\\WerFault.exe",
            "?:\\Windows\\System32\\wermgr.exe",
            "?:\\Windows\\SysWOW64\\wermgr.exe")
'''

[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1548"
name = "Abuse Elevation Control Mechanism"
reference = "https://attack.mitre.org/techniques/T1548/"
[[threat.technique.subtechnique]]
id = "T1548.002"
name = "Bypass User Account Control"
reference = "https://attack.mitre.org/techniques/T1548/002/"



[threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

[internal]
min_endpoint_version = "7.13.0"
